# Generated by Django 4.2.4 on 2023-08-26 05:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(null=True, upload_to=blog.models.user_directory_path, verbose_name='Featured image'),
        ),
    ]
