# Generated by Django 4.2.4 on 2023-08-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_paticipants_blog_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='participants',
            new_name='paticipants',
        ),
    ]
