# Generated by Django 4.2.4 on 2023-08-26 08:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_directory_path, verbose_name='Featured image'),
        ),
    ]
