# Generated by Django 4.2.4 on 2023-08-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_participants_blog_paticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
