# Generated by Django 4.2.4 on 2023-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/avatar.png', null=True, upload_to='avatar/', verbose_name='Profile piture'),
        ),
    ]
